version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: documind_backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LLM_MODEL_NAME=gemini-3.5-flash
      - EMBEDDING_MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: documind_frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
